apiVersion: v1
kind: Pod
metadata:
  name: pod-with-prestop-hook
spec:
  containers:
  - image: knix008/kubia
    name: kubia
    lifecycle:
      preStop:
        exec:
          command: 
          - sh
          - -c
          - "echo 'hook will fail with exit code 15'; exit 15"
