apiVersion: apps/v1
kind: Deployment
metadata:
  name: test
spec:
  replicas: 3
  template:
    metadata:
      name: test
      labels:
        app: test
    spec:
      containers:
      - image: busybox
        name: nodejs
        command:
        - sleep
        - "99999"
  selector:
    matchLabels:
      app: test





