apiVersion: v1
kind: Pod
metadata:
  name: kubia-xyz
  labels:
    app: kubia
spec:
  containers:
  - image: knix008/kubia
    name: kubia
    ports:
    - containerPort: 8080
      protocol: TCP
    resources:
      requests:
        memory: 300Mi
        cpu: .65
