apiVersion: apps/v1
kind: Deployment
metadata:
  name: kubia
spec:
  selector:
    matchLabels:
      run: kubia
  replicas: 3
  template:
    metadata:
      labels:
        run: kubia
    spec:
      containers:
      - name: kubia
        image: knix008/kubia
        ports:
        - containerPort: 8080