apiVersion: v1
kind: Pod
metadata:
  name: kubia
spec:
  containers:
    - name: kubia
      image: knix008/kubia
      ports:
        - containerPort: 8080
          name: http
          protocol: TCP