apiVersion: apps/v1
kind: Deployment
metadata:
  name: kubia
  namespace: default
  labels:
    app: kubia
spec:
  replicas: 1
  selector: 
    matchLabels:
      app: kubia
  template:
    metadata:
      labels:
        app: kubia
    spec:
      containers:
        - name: kubia
          image: knix008/kubia