apiVersion: v1
kind: ReplicationController
metadata:
  name: nginx-rc
spec:
  replicas: 3
  selector:
    app: webserver
    env: prod
  template:
    metadata:
      name: nginx-pod
      labels:
        app: webserver
        env: prod
    spec:
      containers:
      - name: nginx-container
        image: nginx
        ports:
        - containerPort: 8080
