apiVersion: v1
kind: Pod
metadata:
  name: gitrepo-volume-pod
spec:
  initContainers:
  - name: git-clone
    image: alpine/git
    args:
    - clone
    - https://github.com/knix008/Website
    - /repo
    volumeMounts:
    - name: git-repository
      mountPath: /repo
  containers:
  - image: nginx:alpine
    name: web-server
    volumeMounts:
    - name: git-repository
      mountPath: /usr/share/nginx/html
      readOnly: true
    ports:
    - containerPort: 80
      protocol: TCP
  volumes:
  - name: git-repository
    emptyDir: {}
